name: 💡 Improvement
description: Suggest an improvement
title: "💡 <title>"
labels: ["Enhancement"]
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: What do you propose?
  validations:
    required: false
