name: 🙋 Request a range of IDs
description: To add new content you need IDs. Here you get them!
title: "🙋 ID-request"
labels: []
assignees: []
body:
- type: markdown
  id: intro
  attributes:
    value: >
      We track provenance and want to give credit to contributors.
      Therefore, we ask for your [ORCID](https://orcid.org) below.
      If you don't have one, we can use your GitHub name instead.
      In addition you can supply the [ROR](https://ror.org) of the organization you work for.

      Also tell us how many IDs you need.
- type: input
  id: orcid
  attributes:
    label: Your ORCID identifier.
- type: input
  id: ror
  attributes:
    label: The ROR of the organization you work for.
- type: input
  id: count
  attributes:
    label: Number of IDs requested.
- type: textarea
  id: message
  attributes:
    label: Additional information.
    description: Optionally tell us more about your plans.
